name: Update Suttas and CI/Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Merge to gh-pages
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git checkout main
          git pull origin main
          git checkout -b gh-pages
          git push -f origin gh-pages
